### ISSUE TITLE
tga on import not working

### ISSUE THREAD

**Issue by katekittaly** [skarndev/umodel_tools#10]
Whenever I choose tga instead of png from the dropdown menu on import, the dropdown menu continues to say png. The meshes import without textures.

Hogwarts Legacy
Blender 3.4.0
Tried your 1.03 and 1.02 release.

**Comment by skarndev** [comment]
Thanks for reporting. I fixed the issue, try the latest release.

**Comment by katekittaly** [comment]
Thank you so much for the prompt reply and the work on this! It's working for me now.
