### ISSUE TITLE
Unable to import error 13

### ISSUE THREAD

**Issue by weplez13** [skarndev/umodel_tools#13]
I have .json file and when i try to import it i get this error message. 
![image](https://github.com/skarndev/umodel_tools/assets/81298877/004d0c84-e0ef-41f0-af09-6bf952f5d6f9)

**Comment by skarndev** [comment]
Asset directory specified in your settings profile does not allow writing files for regular users. You can either fix this by running your Blender as admin (not recommended) or choosing a different asset directory which is not protected by admin-only access permissions.
